### ISSUE TITLE
Any plan about execute js in java like J2V8 did?

### ISSUE THREAD

**Issue by ddrandy** [seven332/quickjs-android#1]
I noticed some unit tests in module library and it lacks of something like function calls. Hope you could enhance it. I will appreciative for your help.

**Comment by seven332** [comment]
Something like this?
```Java
QuickJS quickJS = new QuickJS.Builder().build();
try (JSRuntime runtime = quickJS.createJSRuntime()) {
  try (JSContext context = runtime.createJSContext()) {
    String script = "" +
        "function fibonacci(n) {" +
        "  if (n == 0 || n == 1) return n;" +
        "  return fibonacci(n - 1) + fibonacci(n - 2);" +
        "}" +
        "fibonacci(10);";
    int result = context.evaluate(script, "fibonacci.js", int.class);
    assertEquals(55, result);
  }
}
```

**Comment by ddrandy** [comment]
TYVM.
Is there a java class that could represent JSObject or JSArray?

**Comment by ddrandy** [comment]
nevermind, I found it.

**Comment by seven332** [comment]
It's still at an early development stage. Basically, I plan to provide APIs like Gson/Moshi to convert between JavaScript value and Java value via TypeAdapter.

**Comment by seven332** [comment]
I believe it's done. Feel free to reopen it.
