### ISSUE TITLE
希望做成第三方依赖。

### ISSUE THREAD

**Issue by YumikoAzu** [seven332/quickjs-android#10]
请教一下，我git clone该项目，发现quickjs没有一起clone下来，这是怎么回事呢？

**Comment by seven332** [comment]
quickjs 是 submodules，直接用 clone 不会下载 submodules。具体的命令写到 readme 里了，到项目首页就能看到。
如果想直接使用，用 jitpack 就行，readme 也写了。

**Comment by YumikoAzu** [comment]
> quickjs 是 submodules，直接用 clone 不会下载 submodules。具体的命令写到 readme 里了，到项目首页就能看到。
> 如果想直接使用，用 jitpack 就行，readme 也写了。

ヾ(≧∇≦谢谢≧∇≦)ノ
