### ISSUE TITLE
Java byte array to Uint8Array

### ISSUE THREAD

**Issue by pierreolivier** [seven332/quickjs-android#11]
Hello ! I already told you that few months ago but your wrapper is amazing ! I have a new request where you could help me :)
Is there any way to create a JS value that is a Uint8Array or an ArrayBuffer ? This array/buffer can be writen thanks to a java byte array or read to a java byte array.

Currently I'm using a loop on each element I want to copy (array.setProperty(i, ...)) in an array created with jsContext.createJSArray(), but it is very very slow. I'm working with 2MB buffers.

Have a good week-end !

**Comment by seven332** [comment]
QuickJS supports ArrayBuffer, QuickJS Android should support it too.
I wiil add some APIs, like java byte[] to js ArrayBuffer.

**Comment by seven332** [comment]
Now you can convert java primitive array to js ArrayBuffer, and convert js ArrayBuffer back to java primitive array.
https://github.com/seven332/quickjs-android/blob/wrapper/library/src/androidTest/java/com/hippo/quickjs/android/JSContextTest.java#L96
https://github.com/seven332/quickjs-android/blob/wrapper/library/src/androidTest/java/com/hippo/quickjs/android/JSArrayBufferTest.java

**Comment by pierreolivier** [comment]
Thanks a lot, it is working great !!
