### ISSUE TITLE
 FYI: another Android QuickJS implementation in the works

### ISSUE THREAD

**Issue by alastaircoote** [seven332/quickjs-android#2]
Congrats on the library so far, it looks great. Just wanted to let you know that there's another effort to use QuickJS on Android. The duktape-android library is switching to QuickJS:

https://github.com/square/duktape-android/pull/136

Not sure if there is any opportunity for collaboration or code sharing there, just wanted to let you know. I have an active interest in using QuickJS on Android so I'll be following this project closely!

**Comment by seven332** [comment]
This project is inspired by duktape-android. What I want most in duktape-android is something like [TypeAdapter](https://github.com/google/gson/blob/master/UserGuide.md#custom-serialization-and-deserialization) in Gson or [JsonAdapter](https://github.com/square/moshi#custom-type-adapters) in Moshi. It makes the conversion between js value and java value convenient. I think the authors/collaborators of duktape-android have no plan on it. Maybe it will raise performance issues. Anyway, I need this feature. So I'm doing it.

I'd like to collaborate or share code if they have a plan on the feature.
