### ISSUE TITLE
How can I use promises ?

### ISSUE THREAD

**Issue by pierreolivier** [seven332/quickjs-android#7]
I congratulate you on the work achieved, the lib will be very very useful to me.
Here is my issue, i cannot make promises working.

```java
QuickJS quickJS = new QuickJS.Builder().build();
JSRuntime runtime = quickJS.createJSRuntime();
JSContext context = runtime.createJSContext();

Method logMethod = Method.create(Void.class, MainActivity.class.getMethod("log", new Class<?>[]{ String.class }));
context.getGlobalObject().setProperty("log", context.createJSFunction(this, logMethod));

context.evaluate("log('before');" +
    "Promise.resolve()" +
    "  .then(function() { log('in promise 1'); })" +
    "  .then(function() { log('in promise 2'); });", "test.js");
```

I should see these 3 lines of log but I'm only seeing `before`. What should I add to make it working ?

**Comment by seven332** [comment]
It's not supported. We need something like `void js_std_loop(JSContext *ctx)` in `quickjs-lib.c` to wait for the promise.

**Comment by seven332** [comment]
What if the promise never be fulfilled or resolved? Maybe we should wait for promises with timeout.

**Comment by seven332** [comment]
Done. Call `JSContext.executePendingJob()` to finish your promises.
https://github.com/seven332/quickjs-android/blob/wrapper/library/src/androidTest/java/com/hippo/quickjs/android/PromiseTest.java

**Comment by pierreolivier** [comment]
Oh thanks ! It is working great :D
