### ISSUE TITLE
create function without specify parameters, any idea?

### ISSUE THREAD

**Issue by HarlonWang** [seven332/quickjs-android#8]
Create function use quickjs-android must be specify parameters:

	JSFunction zeroCompareTo = context.createJSFunction(integer, Method.create(Integer.class, Integer.class.getMethod("compareTo", Integer.class)));

Hopes like this:

		context.createJSFunction("setTimeout", new Callback() {
			public JSValue callFunction(JSValue[] args) {
				//handle some thing
				JSValue firstArg = args[0];
				if( firstArg instanceOf JSString) {
					Log.d("Test", fristArg);
				}

				return null;
			} 
		})

Any idea , thx

**Comment by jwxbond** [comment]
have the same problem. how to solve it?

**Comment by seven332** [comment]
Wow, it's should be supported. I will work on it this weekend.

**Comment by HarlonWang** [comment]
@seven332 thx 👍

**Comment by seven332** [comment]
Done https://github.com/seven332/quickjs-android/commit/3bf22af2e4c76c332b3d2e3b829d09f0f0819d45

**Comment by HarlonWang** [comment]
@seven332 Great job ! :)
