### ISSUE TITLE
请问能否将Java对象的属性或者整个对象注入到JavaScript里头？

### ISSUE THREAD

**Issue by YumikoAzu** [seven332/quickjs-android#9]

**Comment by seven332** [comment]
不是太确定你的问题，能举个具体的例子吗？

**Comment by YumikoAzu** [comment]
> 不是太确定你的问题，能举个具体的例子吗？

像rhino这样-
val bindings = SimpleBindings()
         bindings["result"] = result 绑定一个Java属性到JavaScript那边，然后可以在JavaScript代码直接调用这个result属性。
        

或者j2v8这样-https://github.com/eclipsesource/J2V8/issues/503

**Comment by YumikoAzu** [comment]
> 不是太确定你的问题，能举个具体的例子吗？

rhino-android的例子-https://github.com/gedoor/legado/commit/fad4762fc2da534de091c2f70fe07cf6a3dcf983

**Comment by seven332** [comment]
这种？
https://github.com/seven332/quickjs-android/blob/wrapper/library/src/androidTest/java/com/hippo/quickjs/android/InterfaceTypeAdapterTest.java#L99

**Comment by YumikoAzu** [comment]
> 这种？
> https://github.com/seven332/quickjs-android/blob/wrapper/library/src/androidTest/java/com/hippo/quickjs/android/InterfaceTypeAdapterTest.java#L99

context.getGlobalObject().setProperty 这句感觉应该是我需要的。
😂因为电脑不在身边，就看了readme，没看代码里面的例子。感谢回答！

**Comment by seven332** [comment]
先关了，有问题再开
